# `null` will execut all methods
# list of strings will execute selected methods
method_list: [lofreq_local_haplo,
              shorah_default,
              ]

replicate_count: 1

haplotype_generation: null  # distance or mutation_rate

params_path: config_curlcakes_ONT/params.csv

master_seq_path: null
