method_list: [lofreq_local_haplo,
              cliquesnv_local_haplo,
              ]
replicate_count: 1
haplotype_generation: mutation_rate
params_path: config_mutationrate/params.csv
master_seq_path: null
