method_list: [lofreq_local_haplo,
              shorah_mfa_qualities_unique__1e-4,
              shorah_mfa_qualities_unique__1e-5,
              shorah_mfa_qualities_unique_relative_conv_criteria__1e-3,
              shorah_mfa_qualities_unique_relative_conv_criteria__1e-4,
              shorah_mfa_qualities_unique_relative_conv_criteria__1e-5,
              shorah_mfa_qualities_unique,
              shorah_mfa_qualities_unique,
              shorah_mfa_qualities,
              shorah_mfa_learn_error_param]
replicate_count: 5
haplotype_generation: mutation_rate
params_path: config_mutationrate/params.csv
master_seq_path: null
