# `null` will execut all methods
# list of strings will execute selected methods
method_list: [haploclique, quasirecomb, predicthaplo, haploconduct, cliquesnv]

replicate_count: 10

haplotype_generation: distance  # distance or mutation_rate

params_path: config/params.csv
