method_list: [lofreq_local_haplo,
              shorah_default,
              cliquesnv_local_haplo,
              cliquesnv_local_haplo_snv,
              ]
replicate_count: 5
haplotype_generation: distance
params_path: config_longreads/params.csv
master_seq_path: ../../../../hiv/HXB2.fasta
