---
name: HIV

general:
    aligner: "ngshmmalign"

input:
    reference: "{VPIPE_BASEDIR}/resources/hiv/HXB2.fasta"
    metainfo_file: "{VPIPE_BASEDIR}/resources/hiv/metainfo.yaml"
    gff_directory: "{VPIPE_BASEDIR}/resources/hiv/gffs/"
