---
name: SARS-CoV-2
general:
    aligner: "bwa"

input:
    samples_file: "samples.tsv"
    fastq_suffix: ""
    reference: "resources/sars-cov-2/NC_045512.2.fasta"
    metainfo_file: "resources/sars-cov-2/metainfo.yaml"
    gff_directory: "resources/sars-cov-2/gffs/"
    primers_file: "resources/sars-cov-2/primers/nCoV-2019.tsv"

output:
    snv: true
    local: true
    global: false
    visualization: true

hmm_align:
    leave_msa_temp: true
