---
name: SARS-CoV-2
general:
    aligner: "bwa"

input:
    reference: "{VPIPE_BASEDIR}/resources/sars-cov-2/NC_045512.2.fasta"
    metainfo_file: "{VPIPE_BASEDIR}/resources/sars-cov-2/metainfo.yaml"
    gff_directory: "{VPIPE_BASEDIR}/resources/sars-cov-2/gffs/"
    primers_file: "{VPIPE_BASEDIR}/resources/sars-cov-2/primers/nCoV-2019.tsv"

snv:
    consensus: false

lofreq:
    consensus: false
