# `null` will execut all methods
# list of strings will execute selected methods
method_list: [lofreq_local_haplo,
              cliquesnv_local_haplo,
              cliquesnv_local_haplo_snv,
              ]

replicate_count: 1

haplotype_generation: null  # distance or mutation_rate

params_path: config_realdata_sarscov2/params.csv

master_seq_path: null
