# `null` will execut all methods
# list of strings will execute selected methods
method_list: [lofreq_local_haplo,
              qualhap_use_quality_scores_unique_tiling,
              qualhap_learn_error_params_unique_tiling,
              qualhap_learn_error_params_tiling,
              qualhap_use_quality_scores_tiling,
              shorah_default,
              ]

replicate_count: 1

haplotype_generation: null  # distance or mutation_rate

params_path: config_realdata_sarscov2/params.csv

master_seq_path: null
