method_list: [lofreq_local_haplo,
              shorah_default,
              cliquesnv_local_haplo,
              cliquesnv_local_haplo_snv,
              viloca,
              ]
replicate_count: 2
haplotype_generation: distance
params_path: config_distance/params.csv
master_seq_path: ../../../../hiv/HXB2.fasta
