method_list: [lofreq_local_haplo,
              shorah_default,
              cliquesnv_local_haplo,
              cliquesnv_local_haplo_snv,
              cliquesnv_local_haplo_tf0.01,
              cliquesnv_local_haplo_snv_tf0.01,
              viloca,
              viloca_envp,
              viloca_multi,
              viloca_envp_multi,
              shorah_default_amplicon,
              ]
replicate_count: 5
haplotype_generation: distance
params_path: config_distance/params.csv
master_seq_path: ../../../../hiv/HXB2.fasta
