method_list: [lofreq_local_haplo,
              shorah_default,
              qualhap_use_quality_scores_unique,
              qualhap_learn_error_params_unique,
              qualhap_learn_error_params,
              qualhap_use_quality_scores,
              ]
replicate_count: 5
haplotype_generation: distance
params_path: config_distance/params.csv
master_seq_path: null
