method_list: [lofreq_local_haplo,
              shorah_default,
              viloca,
              cliquesnv_local_haplo,
              cliquesnv_local_haplo_snv,
              ]
replicate_count: 1
haplotype_generation: null
params_path: config_realdata/params.csv
master_seq_path: null
