method_list: [lofreq_local_haplo,
              shorah_default,
              qualhap_use_quality_scores_unique_tiling,
              qualhap_learn_error_params_unique_tiling,
              qualhap_learn_error_params_tiling,
              qualhap_use_quality_scores_tiling,
              ]
replicate_count: 5
haplotype_generation: null
params_path: config_realdata/params.csv
master_seq_path: null
