method_list: [lofreq_local_haplo,
              shorah_default,
              ]
replicate_count: 5
haplotype_generation: mutation_rate
params_path: config_amplicon/params.csv
master_seq_path: ../../../../hiv/HXB2.fasta
