# `null` will execut all methods
# list of strings will execute selected methods
method_list: [lofreq_local_haplo, shorah_mfa_qualities_unique_uniform, shorah_mfa_s1_a0.000001_relaxConv_uniform]

replicate_count: 1

haplotype_generation: null  # distance or mutation_rate

params_path: config_realdata_CoV2/params.csv

master_seq_path: null
