name: Run tutorials

on:
  push:
    branches: gsod-rtd

jobs:
  run-tutorials:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
            sparse-checkout: |
                docs
                tests
            sparse-checkout-cone-mode: false
            lfs: false
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13' 
      - run: |
          cd docs
          mkdir -p _test_tutorials
          python extract_bash_code.py -o _test_tutorials documentation/*.md tutorials/*.md
          cd _test_tutorials
          bash installation.sh
          bash tutorial_hiv.sh